/*
 *
 * AppHomePage constants
 *
 */

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
// get report TMI monthly
export const FETCH_DATA_REQUEST_TMI = 'FETCH_DATA_REQUEST_TMI';
export const FETCH_DATA_SUCCESS_TMI = 'FETCH_DATA_SUCCESS_TMI';
export const FETCH_DATA_FAILURE_TMI = 'FETCH_DATA_FAILURE_TMI';
// get report invoice
export const FETCH_DATA_REQUEST_INVOICE = 'FETCH_DATA_REQUEST_INVOICE';
export const FETCH_DATA_SUCCESS_INVOICE = 'FETCH_DATA_SUCCESS_INVOICE';
export const FETCH_DATA_FAILURE_INVOICE = 'FETCH_DATA_FAILURE_INVOICE';
// get report attachment
export const FETCH_DATA_REQUEST_ATTACHMENT = 'FETCH_DATA_REQUEST_ATTACHMENT';
export const FETCH_DATA_SUCCESS_ATTACHMENT = 'FETCH_DATA_SUCCESS_ATTACHMENT';
export const FETCH_DATA_FAILURE_ATTACHMENT = 'FETCH_DATA_FAILURE_ATTACHMENT';
// get custom junk
export const FETCH_DATA_REQUEST_JUNK = 'FETCH_DATA_REQUEST_JUNK';
export const FETCH_DATA_SUCCESS_JUNK = 'FETCH_DATA_SUCCESS_JUNK';
export const FETCH_DATA_FAILURE_JUNK = 'FETCH_DATA_FAILURE_JUNK';
// get all junk
export const FETCH_DATA_REQUEST_ALLJUNK = 'FETCH_DATA_REQUEST_ALLJUNK';
export const FETCH_DATA_SUCCESS_ALLJUNK = 'FETCH_DATA_SUCCESS_ALLJUNK';
export const FETCH_DATA_FAILURE_ALLJUNK = 'FETCH_DATA_FAILURE_ALLJUNK';
