/*
 *
 * StatusContainer constants
 *
 */
// get data file
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
// delete data
export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE';
// authorize data
export const AUTHORIZE_DATA_REQUEST = 'AUTHORIZE_DATA_REQUEST';
export const AUTHORIZE_DATA_SUCCESS = 'AUTHORIZE_DATA_SUCCESS';
export const AUTHORIZE_DATA_FAILURE = 'AUTHORIZE_DATA_FAILURE';
