/*
 *
 * DashboardContainer constants
 *
 */

export const FETCH_GRAPH_REQUEST = 'FETCH_GRAPH_REQUEST';
export const FETCH_GRAPH_SUCCESS = 'FETCH_GRAPH_SUCCESS';
export const FETCH_GRAPH_FAILURE = 'FETCH_GRAPH_FAILURE';
export const FETCH_GRAPHSIMPLE_REQUEST = 'FETCH_GRAPHSIMPLE_REQUEST';
export const FETCH_GRAPHSIMPLE_SUCCESS = 'FETCH_GRAPHSIMPLE_SUCCESS';
export const FETCH_GRAPHSIMPLE_FAILURE = 'FETCH_GRAPHSIMPLE_FAILURE';
export const FETCH_GRAPHCOMPLETE_REQUEST = 'FETCH_GRAPHCOMPLETE_REQUEST';
export const FETCH_GRAPHCOMPLETE_SUCCESS = 'FETCH_GRAPHCOMPLETE_SUCCESS';
export const FETCH_GRAPHCOMPLETE_FAILURE = 'FETCH_GRAPHCOMPLETE_FAILURE';
